nextstrain/docs.nextstrain.org

environment.yml
conda-forge is a huge package channel that we only needed for
sphinx-markdown-tables and the most recent sphinx_rtd_theme.  Install
the former via pip instead and remove the latter since it's transitively
dep'd through our own theme now.
=> Reduce Conda environment creation time (and thus RTD build time)

environment.yml, src/fetch-docs.py
Thread-based concurrency reduces time in I/O wait.  Connection pooling
eliminates the overhead of the initial TCP connection to the same host.
Making the request from within Python instead of shelling out to curl
avoids the overhead of spawning and managing a new process.
A quicker fetch is much nicer when iterating on docs locally and
frequently rebuilding.
=> Fetch remote documents more quickly

src/guides/install/local-installation.md
Based on [user feedback](https://github.com/openjournals/joss-reviews/issues/2906#issuecomment-748244561), this commit adds instructions for users who already have an older version of Miniconda installed and may need to update their installation before the Nextstrain installation will work.
=> Add instructions to update conda prior to installation

src/guides/share/index.rst, src/guides/share/nextstrain-registry.md, src/guides/share/sars-cov-2.md
So that there are instructions out there for adding builds to this page on nextstrain.org. 
https://github.com/nextstrain/nextstrain.org/pull/248 is important to note here as it adjusts the formatting of that YAML file a bit. 
Would be appreciated to have folks who have recently added builds give this document a quick read through at https://docs.nextstrain.org/en/adding-a-build/guides/share/nextstrain-registry.html and suggest any edits here. cc @cassiawag @barneypotter24
=> Guide: how to add a build to nextstrain.org/sars-cov-2

src/guides/install/local-installation.md
Previous instructions had a few shortcomings, including using `pip` rather than our preferred `python3 -m pip`, failed to update `conda` itself, and failed to update the external dependencies of `augur` which can't be installed by `pip` (`mafft` etc)
=> Improve docs to update a local installation

.gitignore, src/fetch-docs.py, src/tutorials/SARS-CoV-2/index.rst, src/tutorials/index.rst, src/tutorials/tb_tutorial.md, src/tutorials/zika.md
Consolidates introductory tutorials (Zika and TB) into this repository, removes references to the alternate Zika tutorial from the Augur repository, and provides more explanatory titles for each tutorial.
Moving the TB tutorial into this repository allows us to keep the Zika and TB content in the same place.
=> Clean up tutorial organization

src/guides/install/local-installation.md
Given that the Nextstrain conda environment will [soon install Augur and the Nextstrain CLI from Bioconda](https://github.com/nextstrain/conda/pull/11), we can simplify the instructions to update the Nextstrain environment by removing references to pip upgrades of Augur and the CLI.
=> Update instructions to update Nextstrain with Bioconda

Dockerfile, Makefile, README.md
This adds a `Dockerfile` and a `Makefile` target to build the container image and to run it.
This container performs the same actions as the local workflow described in the readme and produces the same results (except for conda environment, which is kept inside the image).
This is purely for convenience and for crazy folks who prefer to sandbox rando software packages from the local machine.
None
No code changes
=> Add docker build

src/index.rst, src/reference/index.rst, src/tutorials/index.rst
As @huddlej put it on slack:
> In addition to listing Nextclade under reference guides, it would be excellent to start integrating Nextclade more into the main docs through tutorials and how-to guides. For some users, Nextclade may be the only part of Nextstrain they need to do their job. If they had a link to “Evaluate the quality of your consensus sequences with Nextclade” as one of the first how-to guides, they would be set without needing to know that Nextclade was initially developed as a separate tool
> [This page](https://docs.nextstrain.org/projects/nextclade/en/latest/user/nextclade-web.html), for example, could be linked with a slightly more explanatory title as one of the first links in the main Nextstrain docs tutorials section
This adds that link to better surface the …
=> Link to nextclade web tutorial

src/conf.py, src/index.rst
Full rewrite, starting from some (less extensive) notes I wrote up
earlier this year describing the different pieces of Nextstrain to
someone.
The intent is to help people construct a mental model of the Nextstrain
ecosystem so they'll find it easier to navigate the docs and know what
they're looking for.  Each paragraph tries to build upon the previous
one to link together terminology, with hyperlinks to the topics
mentioned for immediate jumping off points and further reading.
=> Lay of the land

README.md, src/reference/index.rst, src/tutorials/index.rst
When available.  The ncov subproject currently only has a "latest"
version.  Stable is a friendlier version to link to as it avoids issues
with documentation being ahead of released code.
If toctree supported Intersphinx links, then we wouldn't have these URLs
scattered around; they'd all be in src/conf.py.
=> Consistently link to the "stable" version of subproject docs

.github/workflows/ci.yaml, src/guides/share/index.rst
Expected to fail currently as our docs build has warnings.  Next step is
to resolve the warnings and then keep the build warnings clean.
=> Add a CI job which builds the docs with fatal warnings

src/install.rst
If `-c bioconda` is not included, then mamba will only update primary channel packages.
=> fix: mamba update --all requires explicit inclusion of -c bioconda

src/guides/share/nextstrain-groups.rst
Adds a section about how to remove files to the Nextstrain Groups documentation with examples for removing specific files or a group of files matching a pattern.
Separately, expands the previous reference of `nextstrain remote ls` to `nextstrain remote list` for consistency throughout this page.
Docs were tested locally and [via RTD hook with this PR](https://nextstrain--60.org.readthedocs.build/en/60/guides/share/nextstrain-groups.html#remove-files-from-your-group).
=> Document how to delete files from Groups

src/conf.py
Otherwise, fetch-docs.py may run under a completely different Python
version/environment/install than Sphinx because fetch-docs.py uses
whatever `python` is (via `#!/usr/bin/env python`) while Sphinx may be
invoked explicitly with a non-default Python.  @victorlin observed the
result of that failure mode in the VSCode integration with Sphinx.
=> Run fetch-docs.py under the same Python that Sphinx is running under

src/install.rst
Preview: https://nextstrain--81.org.readthedocs.build/en/81/install.html
After experimenting with Nextstrain installation on different operating systems, there were notable differences that warranted sectioning the guide per OS.
This change rewrites the installation steps with a grouping of tabs per tested OS.
A new Background section is added before installation steps, retaining notable context from the current documentation.
=> Update installation instructions for macOS/Windows/WSL

src/install.rst
No longer needed as of nextstrain-cli 3.0.5 since netifaces not a dep
anymore.  See <https://github.com/nextstrain/cli/pull/138>.
=> Remove Visual C++ toolchain install from Windows installation steps

src/conf.py
This change pulls the current year from [`datetime.now()`](https://docs.python.org/3/library/datetime.html#datetime.datetime.now) for the copyright text.
=> Auto-detect current year for copyright text

.github/workflows/sync-redirects.yaml, README.md, redirects.yml
Automatically synced to RTD using the new readthedocs-cli package I wrote and a new GitHub Actions workflow for this repo.
Includes the `redirects.yml` file I pushed to #84, so it doesn't matter which order merge happens in.
I setup the `RTD_TOKEN` secret on GitHub (using the `nextstrain` RTD user's account) and manually triggered [a test run of the workflow](https://github.com/nextstrain/docs.nextstrain.org/runs/4743056090?check_suite_focus=true). All looks well.
=> Manage RTD redirects using a file in this repo

src/learn/parts.rst, src/reference/glossary.rst, src/tutorials/running-a-workflow.rst
Following nextstrain/cli#142:
> Avoid confusion with other CLIs now that we have a few.
=> Rename CLI term to Nextstrain CLI

data/rtd-maintainers, data/rtd-projects
This helps with some manually-run automation like syncing RTD maintainers for each project.
Related to nextstrain/readthedocs-cli#3.
Since making the original version of this commit, I've already added one person and used the updated files to re-sync quickly.
=> Keep a list of RTD projects and a list of RTD maintainers

environment.yml, src/conf.py, src/install.rst
_[preview](https://nextstrain--102.org.readthedocs.build/en/102/install.html)_
1. Use separate `mamba create` for docker vs. native
- This helps resolve dependencies properly for native, and avoids Python pinning issues such as [1] where Python 3.10 is installed+pinned as latest available with nextstrain-cli, but one of augur's dependencies does not yet support 3.10. Creating the environment with all packages listed will properly resolve to 3.9.
2. Separate install tabs for Docker vs. native.
[1]: https://github.com/bioconda/bioconda-recipes/pull/33757#issuecomment-1072675574.
=> Update docker/native installation steps

README.md
While these docs belong in each subproject (repo), it's nice
to provide pointers here.
~I couldn't find documentation on how to build the CLI docs locally~ There is no documentation for building the CLI docs locally, see https://github.com/nextstrain/cli/issues/131.
=> Add instructions on how to build subproject docs

src/learn/interpret/how-to-read-a-tree.md
Just a minor typo fix. The fully sampled tree is on the left part of the figure. 
None
N/A
=> Fix typo on how-to-read-a-tree.md

redirects.yml, src/fetch-docs.py, src/guides/contribute/documentation.md, src/guides/contribute/index.rst, src/learn/interpret/interacting-with-nextstrain.md
See commit messages for details of the two changes and the [revised Contributing page](https://nextstrain--111.org.readthedocs.build/en/111/guides/contribute/index.html) in the preview build.
=> Rework contributing pages

src/install.rst
[_(preview)_](https://nextstrain--112.org.readthedocs.build/en/112/install.html)
This is for users on Apple Silicon. If emulation is not used, Conda will fail to find packages like `mafft` and `iqtree` since they are not available via `osx-arm64` or `noarch` (similar to https://github.com/nextstrain/cli/issues/14#issuecomment-1063583014 which is why the Native runtime is not an option on Windows without WSL). This is outside of our control, so the best recommendation is to use emulation which has worked well for me personally.
This makes the experience a bit ugly for M1 users. A better scenario would be if nextstrain/docker-base#35 is resolved and benchmarks prove that non-emulated Docker is faster or comparable to emulated Native. Then, this intermediate conda environment will not be the …
=> Add commands to create intermediate conda environment with osx-64 emulation

src/install.rst
[_preview_](https://nextstrain--115.org.readthedocs.build/en/115/install.html)
The Nextstrain Docker image used by the Docker runtime comes with many
other software tools, so that the runtime can work with all core
pathogen workflows. In contrast, the current Native runtime installs a
"bare minimum" set of software, requiring individual workflows to
specify additional installation commands just for the Native runtime.
This commit effectively syncs the two runtimes to provide the same
tools.
In the long term, it would be best to abandon this approach of
supporting *n* pathogen workflows by a single setup (for both Docker and
Native runtime). While this might seem like taking a step backwards by
putting more potentially unused tools in the Native runtime, the
difference of available tools …
=> Install SARS-CoV-2 workflow dependencies in Native runtime

environment.yml, src/conf.py
The new extension already has sphinx_copybutton pre-installed and configured.
https://github.com/nextstrain/sphinx-theme/issues/30
=> Replace sphinx_copybutton with nextstrain.sphinx.theme

src/index.rst, src/install.rst, src/reference/faq.rst
_[(preview)](https://nextstrain--124.org.readthedocs.build/en/124/install.html#installation-steps)_
See FAQ contents for the reasoning behind using the Intel Miniconda
installer on Apple silicon.
- Ideas from https://github.com/nextstrain/docs.nextstrain.org/issues/121#issuecomment-1197224332 and further discussion during a meeting with @tsibley @huddlej @j23414.
=> Use Intel Miniconda installer for Apple silicon, start an installation FAQ page

src/guides/share/index.rst, src/learn/parts.rst
The page was moved in https://github.com/nextstrain/auspice/commit/20be0560a3d881466cb7945699e4c720a815d579.
_N/A_
=> Fix links to Auspice server overview page

src/guides/share/groups/migrate-from-s3.rst
It's different from AWS credentials and so may trip people up. Suggested by @corneliusroemer in Slack.¹
¹ https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1665158683454819
=> groups: Note the lifetime of `nextstrain login` sessions

src/install.rst, src/reference/faq.rst, src/snippets/wsl-home-dir.rst, src/tutorials/creating-a-bacterial-pathogen-workflow.rst, src/tutorials/creating-a-workflow.rst, src/tutorials/running-a-workflow.rst
[Preview](https://nextstrain--123.org.readthedocs.build/en/123/install.html)
---
Reorganizes the tabs to be runtime first then OS (instead of OS then runtime) as I think this makes more sense now that the initial steps of installing and setting up a base Conda env aren't shared.  It also means we don't have multiple levels of ordered lists (steps), which is a nice simplification.
The goal is simplify this installation path quite a bit by avoiding the Python bootstrapping issue.
Reorganizes the tabs to be runtime first then OS (instead of OS then runtime) as I think this makes more sense now that the initial steps of installing and setting up a base Conda env aren't shared.  It also means we don't have multiple levels of ordered lists (steps), which is a nice simplification.
Moves verbose …
=> Use standalone installation of Nextstrain CLI for Docker runtimes

src/index.rst, src/reference/governance.rst
Adds the initial governance document as drafted in Google Docs ([preview on RTD](https://nextstrain--136.org.readthedocs.build/en/136/reference/governance.html)).
=> Add initial version of governance document

src/install.rst, src/reference/faq.rst, src/snippets/conda-install-full-bash.rst, src/snippets/nextstrain-setup-conda.rst
See commit messages for details and read [the preview](https://nextstrain--138.org.readthedocs.build/en/138/install.html).
Related to https://github.com/nextstrain/cli/pull/218 and others in the CLI repo.
Related to #131.
=> install: Add instructions for the Conda runtime

src/learn/augur-to-auspice.rst
In responding to a discussion post¹, I found that augur export will try to guess the appropriate color type if the type is not provided². This commit updates the augur-to-auspice docs to outline this guessing process.
Also added a link to the guide on how to add custom trait colors for users to learn more about the colors TSV file.
¹ https://discussion.nextstrain.org/t/zero-value-for-coloring-in-nextstrain/1266/1 
² https://github.com/nextstrain/augur/blob/8b3c33dd8994ffeccd6e82ba9c06d2cf0499c3e4/augur/export_v2.py#L245-L251
=> augur-to-auspice: update default colorings type

.github/workflows/sync-redirects.yaml
A central copy is easier to maintain over time now that this workflow is
proliferating across our repos.
See also https://github.com/nextstrain/.github/pull/30.
=> Use centralized sync-rtd-redirects workflow

src/install.rst
Related to [this Slack thread](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1670963819691499).
=> install: Document that Rosetta 2 must be enabled for arm64 Macs and how to do so

src/install.rst
Leaves it to the installer to instruct how to enable Rosetta 2 and generally makes the warning a bit less obtrusive.
Related-to: <https://github.com/nextstrain/cli/pull/247>
Related-to: <https://github.com/nextstrain/docs.nextstrain.org/pull/147>
=> install: Revise instructions for Rosetta 2 now that the installer checks for it

src/index.rst, src/reference/data-files.rst
This will be the new canonical version of our intentions, moving them out of our internal document (see initial comment in source).
[Preview page](https://nextstrain--151.org.readthedocs.build/en/151/reference/data-files.html)
=> Add "Data files" page discussing the build and workflow files we publish

src/guides/share/groups/customize.rst
There are many fewer legacy, single-bucket groups than new, multi-tenant bucket groups now.  Document appropriate curl commands, even if they're not ideal.  Better to have instructions to point to than nothing at all.
=> groups/customize: Overhaul page to apply to new groups and include more information

src/install.rst
This is not relevant anymore now that the linked issue is closed (with the introduction of a linux/arm64 variant of the Docker image).
Prompted by closure of https://github.com/nextstrain/docker-base/issues/35
=> Remove warning about Docker runtime on macOS

src/guides/bioinformatics/index.rst, src/guides/bioinformatics/missing-sequence-data.rst
This documentation was motivated by and should close https://github.com/nextstrain/augur/issues/1043
There was a PR (now closed) related to this issue which expanded the functionality of augur mask: https://github.com/nextstrain/augur/pull/1048
[Rendering of the added page (via RTD)](https://nextstrain--158.org.readthedocs.build/en/158/guides/bioinformatics/missing-sequence-data.html)
=> Detail how we handle missing sequence data, gaps etc

src/tutorials/creating-a-workflow.rst
_preview: [before](https://docs.nextstrain.org/en/latest/tutorials/creating-a-workflow.html#setup), [after](https://nextstrain--159.org.readthedocs.build/en/159/tutorials/creating-a-workflow.html#setup)_
The step now applies to all runtime setups. Previously, it relied on inaccurate assumptions:
1. It only supported 2 runtimes, Docker and ambient.
2. If using the ambient runtime, it already had tools available (e.g. a Conda environment is already active).
N/A
=> Update runtime-dependent setup step

redirects.yml, src/index.rst, src/reference/documentation-style-guide.rst, src/reference/snakemake-style-guide.rst
_[preview of new page](https://nextstrain--162.org.readthedocs.build/en/162/reference/snakemake-style-guide.html)_
Publish the internal Snakemake style guide as a page on the public docs.
This was discussed on Slack [[1](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1670353442520569?thread_ts=1670353195.208659&cid=C01LCTT7JNN)] [[2](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1683187533217929)].
=> Add Snakemake style guide

src/reference/snakemake-style-guide.rst
_[preview](https://nextstrain--163.org.readthedocs.build/en/163/reference/snakemake-style-guide.html#access-config-values-appropriately)_
Adding something that I applied in https://github.com/nextstrain/monkeypox/commit/c10fde839c21c18ec96dad82f66d9c6c5737540c which seems fit for this style guide.
Prompted by https://github.com/nextstrain/monkeypox/pull/161#discussion_r1270988193.
=> Add section on using the config var

src/reference/snakemake-style-guide.rst
This was noted in https://github.com/nextstrain/monkeypox/pull/161#discussion_r1281138314.
=> Add section on using lambda for params

src/guides/share/fetch-via-urls.md
Since the colon (:) is reserved as the separator for dual tree displays,
the nextstrain.org server splits paths on the colon.¹ This results in a
404 error as the dataset URL is truncated (e.g. when trying to load
Nextclade dataset ref trees)²
We may update the nextstrain.org server to handle colons in dataset URLs
in the future, but better to note this behavior now in case others run
into the same issue.
¹ https://github.com/nextstrain/nextstrain.org/blob/221c67e5dad919edea65787bc11e4cc2227c42ce/src/endpoints/sources.js#L263
² https://github.com/nextstrain/nextstrain.org/issues/702
=> fetch-via-urls: note colons (:) are not allowed

src/install.rst, src/reference/faq.rst, src/snippets/wsl-home-dir.rst
_Install page: [current](https://docs.nextstrain.org/en/latest/install.html), [preview](https://nextstrain--167.org.readthedocs.build/en/167/install.html)_
Currently, when choosing between the two Windows options, we recommend the WSL interface to Nextstrain as noted in the FAQ page. However, I don't think the installation page reflects this recommendation well enough. To an inexperienced user, the PowerShell interface (named "Windows") might seem like a better option to choose over "WSL on Windows", which conflicts with the recommendation in FAQ.
This PR renames those options to better reflect the recommendation directly on the install page.
N/A
=> install: Recommend WSL more explicitly among Windows options

src/reference/snakemake-style-guide.rst
This old styleguide contains recommendations that are relevant to the pathogen workflows presently maintained.
Prompted by https://github.com/nextstrain/docs.nextstrain.org/pull/162#pullrequestreview-1546026324.
=> Migrate blab/styleguide to the Snakemake style guide

src/reference/snakemake-style-guide.rst
Checking presence of a key in the config should be done with the membership operator. This must be done otherwise false-y values will stay false when membership is checked with `config.get`.
=> Snakemake style guide: Add another way of accessing config values

src/reference/snakemake-style-guide.rst
Adds two recommendations about logging to the Snakemake style guide based on recent difficulty troubleshooting workflow issues with users.
=> Add log recommendations to Snakemake style guide

src/reference/faq.rst, src/snippets/ambient-setup.rst
Ambient runtime users are free to choose whatever means of setup. There are many flavors of Conda, and we should only provide a minimal recommendation.
Furthermore, as of conda 23.10.0, libmamba is now the default solver for conda.¹
¹ <https://github.com/conda/conda/releases/tag/23.10.0>
- Motivated by a recent discovery that [Mamba doesn't work with macOS Sonoma](https://github.com/conda-forge/miniforge/issues/512), but I think a good change even if that wasn't the case.
=> Remove Mamba recommendation

src/install.rst
Only the Conda runtime requires it.
Related-to: <https://github.com/nextstrain/cli/pull/357>
Related-to: <https://github.com/nextstrain/cli/pull/361>
Related-to: <https://github.com/nextstrain/cli/pull/358>
=> install: Rosetta will not be required for Nextstrain CLI itself as of 8.2.0

.gitignore, src/conf.py, src/fetch-docs.py, src/guides/bioinformatics/filtering-and-subsampling.rst, src/guides/bioinformatics/index.rst
Uses a snippet from the Augur docs.
- Closes #187
- Follow-up to https://github.com/nextstrain/augur/pull/1425
=> Add guide on filtering and subsampling

Makefile
Resolves https://github.com/nextstrain/docs.nextstrain.org/issues/193
The double asterisk (`**`) glob expression worked for both sphinx-autobuild-2021.03.14 and sphinx-autobuild-2024.2.4. when I tested locally.
=> livehtml: Update --ignore pattern to use `**`

src/guides/manage-installation.rst, src/install.rst
Descriptive snippet copied from Nextstrain CLI docs.
<https://github.com/nextstrain/cli/blob/6da49c541/nextstrain/cli/runner/singularity.py#L4-L9>
- Suggested in https://github.com/nextstrain/cli/pull/353#issuecomment-1919675153
=> Add instructions for singularity runtime

src/install.rst, src/snippets/ambient-setup.rst
Updated the instructions in the ambient section to make it clear that a particular version of Python should be used. I also modified the overall intent of the instructions slightly, so that they direct the user to set up a new Conda environment. The old instructions were oriented more towards adding Nextstrain to an existing Conda enviroment, which (IMO) seems like a less common scenario, and also one more likely to be undertaken by a more experienced user who will be able to adapt these instructions on the fly; doing it this way also side-steps documenting how somebody would need to modify an existing Conda env with an unsupported version of Python.
#201
=> Update ambient install docs to specify Python version

.gitignore, src/conf.py, src/fetch-docs.py, src/guides/bioinformatics/filtering-and-subsampling.rst
Moving to this project prevents [fetching another external doc](https://github.com/nextstrain/docs.nextstrain.org/blob/2ca0b7266ccdb86bf27dd91f774071fdc133ea0e/README.md#fetching-of-documents-from-other-repositories) and makes for a cleaner split between `augur filter` reference and guide.
- follow-up to https://github.com/nextstrain/augur/pull/1431
=> Move filtering/subsampling docs into this project

src/install.rst, src/snippets/wsl-home-dir.rst
[_preview_](https://nextstrain--207.org.readthedocs.build/en/207/install.html)
See commit messages
fe4abf6 and 7f3f5a77f12f92ca997e15d7a265e5a2036d647e were prompted by debugging in the lab. The rest is stuff that I thought of while re-reading the contents.
=> Update installation section

src/reference/snakemake-style-guide.rst
Makes it so much easier to identify bottlenecks in workflows if they all just start out with benchmarks!
Prompted by https://github.com/nextstrain/ncov-ingest/issues/446
=> Add `benchmark` to the Snakemake style guide

conda.yml
Follow up to https://github.com/nextstrain/docs.nextstrain.org/pull/215
Mirroring https://github.com/nextstrain/ncov/pull/1127
Unpinning docutils to be able to pull in the latest sphinx-argparse which includes upstream fixes for
https://github.com/nextstrain/docs.nextstrain.org/issues/214
=> Unpin docutils + sphinx-argparse

conda.yml, src/conf.py, src/guides/share/groups/migrate-from-s3.rst, src/guides/snapshots.rst, src/learn/augur-to-auspice.rst, src/reference/documentation-style-guide.rst, src/reference/faq.rst, src/tutorials/creating-a-bacterial-phylogenetic-workflow.rst, src/tutorials/creating-a-pathogen-repo/creating-an-ingest-workflow.rst
* Updates minimum required version of Sphinx
* Adds configuration for linkchecking
* Fixes a number of broken links
Link fixes were grouped into a number of small commits to make it easier to update during review, if necessary. 
#14
=> Fix broken links [#14]

src/conf.py, src/guides/share/index.rst
Fixing a couple more links I over-looked in the last set. 
#14
=> More broken links [#14]

src/conf.py
Also add note that the underlying code in the linkchecker uses `re.match()` to evaluate the regular expression, so there's already an implicit start of string anchor in effect, and something like `r'google'` will _NOT_ match anything.
=> Anchor regexes and escape potential metachars [#14]

src/reference/snakemake-style-guide.rst
This greatly enhances the readability of the shell block in Snakemake's log messages and avoids accidentally interpreting escapes too early.
=> snakemake-style-guide: Recommend *raw* triple-quoted strings for shell blocks

src/guides/bioinformatics/filtering-and-subsampling.rst
_[preview](https://nextstrain--222.org.readthedocs.build/en/222/guides/bioinformatics/filtering-and-subsampling.html)_
Prepping for upcoming weighted sampling docs. These changes are applicable to current `augur filter` features.
=> Update filtering and subsampling docs

src/guides/bioinformatics/filtering-and-subsampling.rst
_[preview](https://nextstrain--223.org.readthedocs.build/en/223/guides/bioinformatics/filtering-and-subsampling.html#subsampling-within-augur-filter)_
Adding docs for https://github.com/nextstrain/augur/issues/1318
=> Add weighted sampling docs

src/guides/bioinformatics/filtering-and-subsampling.rst
I started adjusting the sample sizes in "Adjust multiple augur filter section for weighted sampling" (c6084f34) but did not properly follow through with the rest of the section. Changes:
- 100 → 200 sequences from Washington state
-  50 → 100 sequences from the rest of the United States
Follow-up to #223.
=> Fix tiered subsampling example

conda.yml
conda-forge is completely open, Anaconda is not.
=> dev: Use conda-forge not the Anaconda default channels

src/conf.py
In sphinx-rtd-theme version 3.0.0, `display_version` was removed in favor of `version_selector` and `language_selector`.
#216
=> Changes for sphinx-rtd-theme 3.0.0

src/tutorials/creating-a-pathogen-repo/creating-an-ingest-workflow.rst
The old link returned 404 with a client-side redirection to the new link.
=> Fix broken link to influenza naming conventions

Makefile
No reason not to allow this.
Prompted by https://github.com/nextstrain/.github/pull/110/commits/6332153c6a30416281bad48c0187054546ee6564 while debugging https://github.com/nextstrain/.github/pull/110
=> Allow BUILDDIR to be set from environment

make.bat
Follow-up to #233 where I failed to follow through with copy/paste adjustments.
=> make.bat: Fix BUILDDIR from environment

src/reference/ca-certificates.rst
This is an important detail that someone generally unfamiliar with these configurations would easily miss and then wonder why their certs weren't being picked up.  The requirement applies not just to applications using OpenSSL, but often also to applications that use other TLS libraries and support SSL_CERT_DIR for compatibility.
=> reference/ca-certificates: Note that running c_rehash on SSL_CERT_DIR is required

src/reference/ca-certificates.rst
Not having to say here, "There's nothing you can do", was the driving reason for me adding said configurability to Nextclade in the first place!
Related-to: <https://github.com/nextstrain/nextclade/pull/1536>
=> reference/ca-certificates: Update Nextclade section with its new configurability

src/fetch-docs.py, src/reference/data-formats.rst
_[docs preview](https://nextstrain--238.org.readthedocs.build/en/238/reference/data-formats.html)_
Add TSV section to the Data Format docs, based on discussion in https://github.com/nextstrain/augur/issues/1566.
Resolves https://github.com/nextstrain/docs.nextstrain.org/issues/237
=> Data format: TSV

src/conf.py, src/reference/data-formats.rst
_[docs preview](https://nextstrain--239.org.readthedocs.build/en/239/reference/data-formats.html)_
Prompted by @jameshadfield's request
<https://github.com/nextstrain/docs.nextstrain.org/pull/238#issuecomment-2515664328>
Snippets are simplified versions of TSV handling in Augur.
Follow up to https://github.com/nextstrain/docs.nextstrain.org/pull/238
=> data-formats: Add example Python snippets for TSV handling

src/conf.py
This link has failed multiple times in the GH Actions workflow even though it succeeds when running linkcheck locally. Ignore link for now and we can revisit later if desired.
=> Ignore gnu link for linkcheck

src/guides/bioinformatics/filtering-and-subsampling.rst
_[(preview)](https://nextstrain--245.org.readthedocs.build/en/245/guides/bioinformatics/filtering-and-subsampling.html#weighted-sampling)_
Add a more advanced example with multiple grouping columns and default of 0 to effectively exclude sequences.
=> Add second weighted sampling example

src/tutorials/creating-a-phylogenetic-workflow.rst
Adds a link to the [VEME 2022 tutorial repo](https://github.com/nextstrain/veme-2022).
Closes #241
=> Link to VEME 2022 tutorial repo [#241]

src/reference/snakemake-style-guide.rst
The previous example using `2>&1 | tee {log:q}` did not work well in these scenarios:
1. When there is a piped chain of commands – only the last command's output gets redirected properly.
2. When a command uses `>` to redirect stdout to an output file – stderr is mixed into stdout and nothing ends up in the console output or log file.
The updated example covers those scenarios.
Closes #250
=> Use exec for more robust logging

src/reference/snakemake-style-guide.rst
This was meaningful when the recommendation was
… | tee {log:q}
It no longer makes sense with changes from #251.
There's still an argument to be made that pipefail should be used with pipes in general, but that is more about shell scripting and does not need to be explicitly mentioned given that Snakemake uses bash's strict mode by default.
Follow-up to https://github.com/nextstrain/docs.nextstrain.org/pull/251#discussion_r2087464717
=> Remove paragraph on pipefail with tee

src/snippets/ambient-setup.rst
This was previously only used by the ncov workflow, which has [stopped](https://github.com/nextstrain/ncov/commit/b52f0e172654413a1f64ecb9150fcf1176af2a7d) using it. It has also been removed in the [docker](https://github.com/nextstrain/docker-base/commit/50cf352ae9be7eed36c43f91941ffc4b264f69ac) and [conda](https://github.com/nextstrain/conda-base/commit/560e502589bf237eb66b94428f58e8b9528497a4) runtimes.
- https://github.com/nextstrain/ncov/pull/1164
- https://github.com/nextstrain/docker-base/pull/237
- https://github.com/nextstrain/conda-base/pull/14
=> Remove pangolin and pangolearn

src/learn/augur-to-auspice.rst
_[preview](https://nextstrain--224.org.readthedocs.build/en/224/learn/augur-to-auspice.html#configuring-coloring-names-and-types)_
Adding info about how to use different colouring types in the config file - what format data should be and how the colours/legend will look
=> Update help about coloring types

src/learn/augur-to-auspice.rst
Measles auspice config file name was changed in 
<https://github.com/nextstrain/measles/pull/62>
This borked link was flagged in a separate CI workflow for nextstrain/.github <https://github.com/nextstrain/.github/actions/runs/15496400390/job/43634037676>
=> Fix measles links

src/guides/bioinformatics/filtering-and-subsampling.rst
Adds a missing equals sign to pandas-style query strings to fix a runtime query syntax error.
=> Fix typo in pandas-based query example
