nextstrain/docs.nextstrain.org

.gitmodules, readthedocs.yml, src/conf.py, src/tutorials/SARS-CoV-2/index.rst, src/tutorials/index.rst
An example of how to incorporate documents from other repositories (#3 ) using git submodules. Still some general issues with formatting to be discussed in this context.
=> Migrate ncov tutorial

src/guides/share/community-builds.md
Unrelated to the content of this commit, it would be nice were
wide tables able to take up more than the current 800px max
width on wide screens.
The previous page was confusing as it was so out of date!
What is the goal of this pull request? What does this pull request change?
Fixes #  
Related to #  
What steps should be taken to test the changes you've proposed?  
If you added or changed behavior in the codebase, did you update the tests, or do you need help with this?
=> Update community dataset page

src/tutorials/zika.md
Adds a section to the Zika tutorial describing how to run the augur index command and why you would want to do so.
=> Document how to use the augur index command

src/guides/share/sars-cov-2.md
see https://github.com/nextstrain/nextstrain.org/pull/284
=> dont conflate build, dataset;

src/guides/share/nextstrain-groups.rst
As of <https://github.com/nextstrain/nextstrain.org/pull/478>.  Thanks
to @joverlee521 for the prompt to update this.
=> Document changes to group-overview.md frontmatter

src/install.rst
More info: https://github.com/nextstrain/docker-base/issues/35
=> Warn about slow macOS+Docker on install page

src/guides/share/groups/migrate-from-s3.rst
Dates still to be determined for now pending internal migrations first
and some questions around the CLI behaviour.
Related to #104
=> groups: Revise timeline since we didn't start as quickly as I hoped

src/install.rst
Various nits I noticed today in the installation instructions. See commit messages for details. I think these are likely to be uncontroversial, but I'll wait for review to make sure.
=> Install nits

src/install.rst
This will help users who may be confused on how to access Windows files
from WSL.
Closes #114.
_N/A_
=> Add hint to create Windows homedir symlink in WSL

src/install.rst
Use an existing variable to get the link's source path.
- Related to https://github.com/nextstrain/docs.nextstrain.org/pull/128#discussion_r951947234
=> Simplify WSL symlink recommendation

.gitignore, Makefile, README.md, environment.yml
Super handy for edit/preview cycles in dev:
make livehtml
Then open <http://localhost:8000>.
=> dev: Add "livehtml" make target using sphinx-autobuild

src/reference/data-formats.rst
Add measurements sidecar to data formats page. 
Resolves #90
=> data-formats: Add section for measurements sidecar

src/learn/augur-to-auspice.rst
I had trouble finding this guide as I searched for `auspice_config.json` and got no hit.
So I added a few instances of `auspice_config.json` to improve findability.
=> edit: mention `auspice_config.json` for improved searchability

src/install.rst, src/reference/faq.rst, src/reference/glossary.rst
In anticipation of upcoming changes to the Nextstrain CLI [[1]].
[1]: https://github.com/nextstrain/cli/pull/218
_N/A_
=> Update runtime names

.github/workflows/sync-redirects.yaml
Nice to see what would happen!
#141
=> dev: Dry run syncing of RTD redirects for PRs

src/tutorials/narratives-how-to-write.rst
_[(preview)](https://nextstrain--146.org.readthedocs.build/en/146/tutorials/narratives-how-to-write.html)_
Some things I thought of while going through the document.
_N/A_
=> Update narratives tutorial

src/conf.py, src/index.rst, src/reference/style.rst
before / after
See commit messages for details.
=> Add "Components" section to our TOC

src/guides/share/groups/customize.rst
Separates the page into descriptions of the customizable components and the different methods to update them.
Depends on the changes from https://github.com/nextstrain/nextstrain.org/pull/671 being deployed to the production.
See preview of the page: https://nextstrain--156.org.readthedocs.build/en/156/guides/share/groups/customize.html
=> groups/customize: Overhaul page to add web interface option

src/guides/share/groups/index.rst, src/guides/share/groups/migrate-from-s3.rst, src/learn/groups/index.rst
Removes the page from the TOC but keeps it around for reference.
=> groups/migrate-from-s3: Final update now that the migration is complete

src/install.rst, src/reference/faq.rst
This hopefully clarifies a term we use without really explaining it, and at least provides a pointer to more details for those who want to know more.
Related-to: <https://github.com/nextstrain/cli/pull/303>
=> faq: Add a "What's a runtime?" entry summing them up and pointing to the new runtimes documentation

src/snippets/ambient-setup.rst
Add ncbi-datasets dependency, since we transitioned from NCBI Virus to NCBI Datasets.
* https://github.com/nextstrain/monkeypox/pull/179
* https://github.com/nextstrain/monkeypox/pull/211
* https://github.com/nextstrain/dengue/pull/13#pullrequestreview-1675235743
=> doc: transition from ncbi virus to ncbi datasets

src/snippets/ambient-setup.rst
Prompted by https://github.com/nextstrain/measles/pull/10#discussion_r1465761518
These have become common commands used across Nextstrain pathogen repos¹ since they were added to the Docker runtime²
¹ https://github.com/search?q=org%3Anextstrain+AND+%28%22csvtk%22+OR+%22tsv-select%22+OR+%22seqkit%22%29&type=code 
² https://github.com/nextstrain/docker-base/commit/992c575afa14e2b48b87d344a4643d6ff28f98d8
=> ambient-setup: Add csvtk, seqkit, and tsv-utils

src/guides/snapshots.rst
Changes via <https://github.com/nextstrain/nextstrain.org/pull/783>
Merge should wait until we've promoted next.nextstrain.org -> nextstrain.org
=> Update versions / snapshots docs

src/learn/augur-to-auspice.rst, src/tutorials/creating-a-pathogen-repo/creating-an-ingest-workflow.rst, src/tutorials/running-a-phylogenetic-workflow.rst, src/tutorials/using-a-pathogen-repo/running-an-ingest-workflow.rst
Be explicit about code-block language to get the proper syntax highlighting. Prompted by post-merge review
https://github.com/nextstrain/docs.nextstrain.org/pull/195#discussion_r1572774418
=> Fill in missing code-block language

src/reference/governance.rst
[_(preview)_](https://nextstrain--199.org.readthedocs.build/en/199/reference/governance.html)
Keeping up to date.
=> Update governance page

src/reference/governance.rst
_[preview](https://nextstrain--206.org.readthedocs.build/en/206/reference/governance.html)_
=> governance: Add entry for SAB

readthedocs.yml
We had to bump this for Auspice¹, so doing the same across all other RTD projects.
¹ <https://github.com/nextstrain/auspice/commit/2add06aaf0ae6ba1802c1b9c2cfadf3707941d49>
- https://github.com/nextstrain/docs.nextstrain.org/issues/209
=> Bump mambaforge to 23.11

src/tutorials/creating-a-pathogen-repo/creating-an-ingest-workflow.rst
[preview for "Creating an ingest workflow"](https://nextstrain--213.org.readthedocs.build/en/213/tutorials/creating-a-pathogen-repo/creating-an-ingest-workflow.html#curation-steps)
---
Updating the docs to match the changes made in
<https://github.com/nextstrain/pathogen-repo-guide/pull/53>
Resolves https://github.com/nextstrain/docs.nextstrain.org/issues/212
=> Replace references to vendored scripts with augur curate subcommands

conda.yml
Resolves https://github.com/nextstrain/docs.nextstrain.org/issues/214
=> Pin sphinx-argparse <0.5.0

src/conf.py, src/index.rst, src/reference/ca-certificates.rst
This information is a distillation of guidance and assistance I've provided to CDC and other downstream users over the years.  I extracted it from my various notes and recollections and verified some specific behaviour anew.  An official reference page will be useful for pointing users to in the future, and serves as a collection point for future recommendations/information uncovered in troubleshooting sessions.
Related-to: <https://github.com/nextstrain/ncov/issues/1055>
Related-to: <https://github.com/nextstrain/nextclade/issues/726>
=> reference: Document how to configure/modify CA certificate trust stores

src/tutorials/creating-a-pathogen-repo/creating-an-ingest-workflow.rst
Updating docs to reflect changes in
<https://github.com/nextstrain/pathogen-repo-guide/pull/81>
Part of https://github.com/nextstrain/public/issues/17
=> creating-an-ingest-workflow: Remove use of ncov-ingest geolocation rules
